theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
color-modes = true
auto-save = true

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.insert.k]
j = ["normal_mode"]

[keys.insert]
A-h = ["move_char_left"]
A-j = ["move_visual_line_down"]
A-k = ["move_visual_line_up"]
A-l = ["move_char_right"]

[keys.normal]
A-s = "goto_word"
A-1 = ":sh alacritty"
A-2 = ":sh thunar"
A-3 = ":sh alacritty -e octodown"
A-4 = ":sh alacritty -e live-server"
A-5 = ":theme base16_default_light"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-c = "copy_selection_on_next_line"
A-t = ["yank_to_clipboard", ':append-output tgpt -c "$(xclip -o -sel clip)"']
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
C = ["ensure_selections_forward", "extend_to_line_end", "delete_selection", "insert_at_line_end"]
Y = ["ensure_selections_forward", "extend_to_line_end", "yank", "flip_selections"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
esc = ["collapse_selection"]
r = ["collapse_selection", "replace"]

[keys.normal.g]
x = ["expand_selection", "yank_to_clipboard", ':sh sleep 0.1; xdg-open "$(xclip -o -sel clip)"']

[keys.normal."space"]
i = [':append-output mkdir -p img; name=$(date +"%H_%M_%S_%d_%m_%Y").png; xclip -sel clip -t image/png -o > img/$name; echo "![](img/$name)"']

[keys.select]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-t = ["yank_to_clipboard", ':append-output tgpt -c "$(xclip -o -sel clip)"']
